version: '2'
services:
    serverdatamicroservice-mongodb:
        container_name: serverdatamicroservice-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/ServerDataMicroservice/mongodb/:/data/db/
